sudo: required
dist: trusty
language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install ansible git aptitude python-heatclient
  - git clone https://github.com/mpeuster/containernet.git
  - cd containernet/ansible/
  - sudo ansible-playbook -i "localhost," -c local install.yml
  - cd
  - git clone https://github.com/CN-UPB/son-emu.git
  - cd ~/son-emu/ansible
  - sudo ansible-playbook -i "localhost," -c local install.yml


  - python setup.py build
install:
  - "python setup.py install"
script:
  - "python setup.py test"
  - cd ~/son-emu
  - sudo python src/emuvim/examples/simple_heat_restapi_single_dc_sandman1.py




