sudo: required
dist: trusty
language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  - PYTHONPATH=$PYTHONPATH:~/son-emu/src/
  - PYTHONPATH=$PYTHONPATH:~/son-emu/src/emuvim/
  - PYTHONPATH=$PYTHONPATH:~/son-emu/src/emuvim/test/unittests/

before_install:
  - export PYTHONPATH=$PYTHONPATH:~/son-emu/src/
  - export PYTHONPATH=$PYTHONPATH:~/son-emu/src/emuvim/
  - export PYTHONPATH=$PYTHONPATH:~/son-emu/src/emuvim/test/unittests/
  - sudo apt-get update
  - sudo dpkg -l | grep postgres
  - sudo apt-get install --reinstall dpkg
  - sudo apt-get remove postgresql-9.1 postgresql-9.2 postgresql-9.3 postgresql-9.4 postgresql-9.5 postgresql-common postgresql-9.1-postgis-2.2-scripts postgresql-9.2-postgis-2.2-scripts postgresql-9.3-postgis-2.2-scripts postgresql-9.4-postgis-2.2-scripts postgresql-9.5-postgis-2.2-scripts postgresql-client postgresql-client-9.3 postgresql-client-9.5 postgresql-client-common postgresql-common postgresql-9.1-postgis-2.2 postgresql-9.2-postgis-2.2 postgresql-9.3-postgis-2.2 postgresql-9.4-postgis-2.2 postgresql-9.5-postgis-2.2
  - sudo aptitude -o Dpkg::Options::=--force-confold -y upgrade
  - sudo apt-get install ansible git aptitude python-heatclient
install:
  - sudo git clone https://github.com/mpeuster/containernet.git
  - cd containernet/ansible/
  - pwd
  - sudo pwd
  - sudo ansible-playbook -i "localhost," -c local install.yml
  - cd
  - sudo git clone https://github.com/hafer1992/son-emu.git
  - cd ~/son-emu/ansible
  - pwd
  - sudo ansible-playbook -i "localhost," -c local install.yml
  - cd ~/son-emu
  - pwd
  - sudo export PYTHONPATH=$PYTHONPATH:~/son-emu/src/
  - sudo export PYTHONPATH=$PYTHONPATH:~/son-emu/src/emuvim/
  - sudo export PYTHONPATH=$PYTHONPATH:~/son-emu/src/emuvim/test/unittests/

script:
  - sudo -E python src/emuvim/test/unittests/test_heatapi.py



