sudo: required
dist: trusty
language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install ansible git aptitude python-heatclient
  - git clone https://github.com/mpeuster/containernet.git
  - cd containernet/ansible/
  - sudo ansible-playbook -i "localhost," -c local install.yml
  - cd ..
  - sudo python examples/dockerhosts.py
  - python setup.py build
  - python setup.py install
install:
  - "python setup.py install"
script:
  - "python setup.py test"




