sudo: required
dist: trusty
language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  - PYTHONPATH=$PYTHONPATH:~/son-emu/src/emuvim/test/unittests/

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git aptitude python-heatclient curl python-dev python-zmq libzmq-dev libffi-dev libssl-dev python-pip 
  - sudo pip install --upgrade pip
  - sudo pip install docker==2.0.2
install:
  - sudo git clone https://github.com/mpeuster/containernet.git ~/containernet
  - cd ~/containernet
  - sudo python setup.py install
  - sudo pip install Flask simplejson
  - sudo git clone https://github.com/CN-UPB/son-emu.git ~/son-emu
  - cd ~/son-emu/
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then sudo git pull --no-edit origin pull/$TRAVIS_PULL_REQUEST/head ; fi
  - sudo python setup.py install
  - cd ~/son-emu

script:
  - sudo PYTHONPATH=$PYTHONPATH:~/son-emu/src/emuvim/test/unittests/ python src/emuvim/test/unittests/test_heatapi.py



